version: '3.8'

services:
  app:
    image: node:16.17.1-alpine3.15
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scrollrack
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql